language: go
sudo: required

go:
- "1.12.7"

services:
  - docker

before_install:
  - sudo pip install docker-compose

script: go run .ci/cmd/prepare/main.go && sleep 5 && go test tests/*_test.go && go run .ci/cmd/cleanup/main.go
